apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: kube-system
spec:
  containers:
  - args:
    - -c
    - |
      sleep 9999
    command:
    - /bin/sh
    image: oklischat/netshoot:latest
    name: tester
    resources:
      limits:
        cpu: "1"
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10Mi
  preemptionPolicy: PreemptLowerPriority
  hostNetwork: true
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
